language: java

os:
  - linux

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

addons:
  apt:
    packages:
      - autoconf
      - javahelp2
      - tidy
      - liblcms2-dev
      - libtiff4-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf clang-omp libtiff little-cms2 pkg-config; fi

script:
  - ant -f linux/build.xml

