language: java
dist: trusty

os:
  - linux

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

addons:
  apt:
    packages:
      - autoconf
      - javahelp2
      - tidy
      - liblensfun-dev
      - liblcms2-dev
      - libtiff4-dev

before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf clang-omp libtiff little-cms2 pkg-config; fi

script:
  - ant -f linux/build.xml

