language: java
script: ant -f linux/build.xml
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf javahelp2 tidy liblcms2-dev libtiff4-dev
