language: java
script: ant -lib /usr/share/java/ivy.jar -f linux/build.xml
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tidy javahelp2
